USE sociaalhuis; 
DROP TABLE IF EXISTS sh_sectoren; 

CREATE TABLE sh_sectoren ( 
	secID INT NOT NULL AUTO_INCREMENT, 
	CONSTRAINT PRIMARY KEY(secID), 
	secNaam VARCHAR (255) CHARACTER SET UTF8 NOT NULL,
    secInfo VARCHAR (255) CHARACTER SET UTF8 NULL
) engine=innoDB;